#!/bin/bash

# Make sure this command placed/lined into ~/bin and called gitDiff
# Also: add the following to .bash_profile:
#     export GIT_EXTERNAL_DIFF=$HOME/bin/gitDiff

/usr/bin/xxdiff "$2" "$1"
exit 0
