#!/bin/bash

# Copyright (c) 2008-2012, James Philip Rowell,
# Orange Imagination & Concepts, Inc.
# www.orangeimagination.com
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# 
#   - Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#   - Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in
#     the documentation and/or other materials provided with the
#     distribution.
#   - Neither the name "Orange Imagination & Concepts, Inc." nor the
#     names of its contributors may be used to endorse or promote
#     products derived from this software without specific prior written
#     permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# prepSedScript - helpful util to take a file of two collumns of words,
# Eg.:
#
# word1 word2
# word3 word4
#
# ... and turn it into this:
#
# 1,$ s/word1/word2/g
# 1,$ s/word3/word4/g

set +o noclobber
cmdName=`basename "$0"`

cleanup() {
    /bin/rm /tmp/tmpPREPSED$$ > /dev/null 2>&1
    exit 0
}

trap cleanup INT

usageExit() {
    echo "Usage: $1 [-h | --help] [FILE]..."
    if [ "$2" = help ]; then
        cat - <<EOF


$cmdName is a helpful util to take a file of two columns of words,
Eg.:

    word1 word2
    word3 word4

... and turn it into this:

    1,$ s/word1/word2/g
    1,$ s/word3/word4/g

Options:
 -h, --help          Display this help and exit
 -s, --swap          Swap the order of word1 and word2

Note: To get rid of all the crufty leftovers:
    find . -name '.*.$cmdName' -type f -print0 | xargs -0 /bin/rm -f

EOF
    fi
    exit 1
}

#
# Parse options.  Stop when you get to the file list.
#
while :
do
    case "$1" in
        -h|--help) usageExit $cmdName help
        ;;

        -s|--swap) swapWords=yes
	    shift
        ;;

        -*) echo "$cmdName: ERROR: Invalid option '$1'."
             usageExit $cmdName
        ;;

        *) break # We're done processing arguments, so let's get on with it.
    esac
done

echo '#!/bin/bash' >  .$cmdName.undo.$cmdName
echo cd `pwd`      >> .$cmdName.undo.$cmdName
echo '#!/bin/bash' >  .$cmdName.diff.$cmdName
echo cd `pwd`      >> .$cmdName.diff.$cmdName
chmod +x .$cmdName.undo.$cmdName .$cmdName.diff.$cmdName
echo '( set -x' >> .$cmdName.diff.$cmdName

while  [ $# -ne 0 ]
do
    i="$1"

    if  [ -f "$i" ] && [ -w "$i" ]; then
	if [ "$swapWords" = yes ]; then
	    awk '{print $2, $1}' < "$i" | sed -e '1,$ s- -/-' | sed -e '1,$ s-.*-1,$ s/&/g-' > /tmp/tmpPREPSED$$
	else
	    sed -e '1,$ s- -/-' "$i" | sed -e '1,$ s-.*-1,$ s/&/g-' > /tmp/tmpPREPSED$$
	fi
	cmp "$i" /tmp/tmpPREPSED$$ > /dev/null 2>&1
	if [ $? -eq 1 ]; then
            d=`dirname "$i"` 
            f=`basename "$i"`
            /bin/cp "$i" "$d"/."$f".$cmdName
            echo /bin/cp \""$d"\"/.\""$f"\".$cmdName \""$i"\" >> .$cmdName.undo.$cmdName
            echo "/usr/bin/diff \""$d"\"/.\""$f"\".$cmdName \""$i"\"; echo" >> .$cmdName.diff.$cmdName
	    /bin/mv -f /tmp/tmpPREPSED$$ "$i"
	fi
    fi
    if [ ! -w "$i" ]; then
        echo $cmdName: WARNING: "$i" not writeable, no change made.
    fi
    shift
done

echo ') 2>&1 | grep -v "^+ echo" | less' >> .$cmdName.diff.$cmdName

cleanup
