#!/bin/bash

# 3-Clause BSD License
#
# Copyright (c) 2008-2025, James Philip Rowell,
# Alpha Eleven Incorporated
# www.alpha-eleven.com
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in
#     the documentation and/or other materials provided with the
#     distribution.
#
#  3. Neither the name of the copyright holder, "Alpha Eleven, Inc.",
#     nor the names of its contributors may be used to endorse or
#     promote products derived from this software without specific prior
#     written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# test_rm-spaces - Run the rm-spaces regression tests.

usage_exit() {
    echo "Usage: ${0##*/} [-h | --help] [--test-system-rm-spaces]"
    if [ "$1" = help ]; then
	cat - <<@eof

${0##*/} Run regression tests on rm-spaces. Must be run in the
<vfxTdUtils-repository>/tests directory.

Options:

 -h, --help         show this help and exit
 --test-system-rm-spaces run the regression tests on the version of
                    rm-spaces installed on the system. Output test
                    results to appropriatly named file.

@eof
    fi
    exit 1
}

TEST_SYSTEM_RMSPACES=no

#
# Parse options.  Stop when you get to the file list.
#
shopt -s extglob
while :
do
    case "$1" in
        -h|--help) usage_exit help
        ;;

        --test-system-rm-spaces) TEST_SYSTEM_RMSPACES=yes
             shift
        ;;

        --*|-*) usage_exit
        ;;

        *) break # We're done processing arguments, so let's get on with it. :-)
    esac
done

export LC_ALL=POSIX

# !!! This script MUST be run from the 'tests'
# !!! directory in the renumSeq git repo for this to work.
#
export TEST_DIR=`pwd`

if [[ `basename $TEST_DIR` != 'tests' ]]; then
    echo $0: error: not running from tests directory, aborted.
    exit 1
fi

export REPO_DIR=`dirname $TEST_DIR`

unalias rm-spaces > /dev/null 2>&1
unalias rm > /dev/null 2>&1

tmpArgs=/tmp/tmpARGS_RMSPACES.$$
tmpfile=/tmp/tmpTEST_RMSPACES.$$

cleanup() {
    /bin/rm $tmpArgs > /dev/null 2>&1
    /bin/rm $tmpfile > /dev/null 2>&1
    exit 0
}

trap cleanup INT

TEST_OUT_FILENAME=test_rm-spaces.out.`uname`.new

if [ "$TEST_SYSTEM_RMSPACES" = no ]; then
    ln -sf ../scripts/rm-spaces rm-spaces

    if [[ ! ":$PATH:" == *":$TEST_DIR:"* ]]; then
        export PATH="$TEST_DIR:$PATH"
    fi
else
    /bin/rm rm-spaces > /dev/null 2>&1 # In case softlink is in this dir.
    TEST_OUT_FILENAME=test_rm-spaces.out.`uname`.installed.new
fi

echo "Test is using " `which rm-spaces`

export RmSp_TESTDIR=rm-spaces_testdir

# Double check sensible REPO_DIR value before removing old testdir
#
if [ -z "$REPO_DIR" ]; then
    echo $0: error: REPO_DIR was empty, dangerous recursive rm avoided.
    exit 1
elif [[ "$REPO_DIR" == "/" ]]; then
    echo $0: error: REPO_DIR set to root, dangerous recursive rm avoided.
    exit 1
elif [[ `basename $REPO_DIR` != 'vfxTdUtils' ]]; then
    echo $0: error: REPO_DIR might not be set to vfxTdUtils repo, dangerous recursive rm avoided.
    exit 1
fi
rm -rf $TEST_DIR/$RmSp_TESTDIR/*

# Create list of test directories needed.
# Then touch the file names to make testfiles.
# Note: pwd should still be $TEST_DIR
#

*** left off here JPR

cat createTestData_rm-spaces/create.?Test.files | sed -e '1,$ s/\/[^\/]*$//' | sort -u > $tmpfile
mkdir -p `cat $tmpfile`
touch `cat createTestData_rm-spaces/create.?Test.files`
chmod 666 `cat createTestData_rm-spaces/create.?Test.files`

# The following are tests. One test per line.
# The first item on a line is the directory relative to
#     $TEST_DIR/testdir to run the test in.
# The second is the command to run.
# The rest are args to the command.
#
cat << EOF > $tmpArgs
.   uname
.   rm-spaces                                # Run with no args - should do nothing
.   rm-spaces --version                      # MUST increment with each update/bug fix, corresp w/ release.
.   rm-spaces --help                         # To keep track of changes with help, plus check if correct
.   rm-spaces --noSuchArg                    # To check error checking of args
EOF

export NUM_TESTS=`wc -l < $tmpArgs`

echo ------ Begin Tests ------ > $TEST_DIR/$TEST_OUT_FILENAME

set -f # Turn off globbing
i=1
while true; do
    declare -a args=(`sed -n -e "$i p" $tmpArgs | sed -e 's/#.*//' `)
    if [ ${#args[@]} -eq 0 ]; then
        break;
    fi
    workingDir=${args[0]}
    cmd=${args[1]}
    args=(${args[@]:2})
    echo "" >> $TEST_DIR/$TEST_OUT_FILENAME
    echo --- Test $i of $NUM_TESTS ---
    echo ----- Test $i -+- dir: $workingDir -+- $cmd ${args[@]} ----- >> $TEST_DIR/$TEST_OUT_FILENAME
    cd $TEST_DIR/$RmSp_TESTDIR/$workingDir
    $cmd ${args[@]} >> $TEST_DIR/$TEST_OUT_FILENAME 2>&1
    retVal=$?
    if [ $retVal -ne 0 ]; then
        echo "--+--  $cmd returned non-zero error code: $retVal  --+--" >> $TEST_DIR/$TEST_OUT_FILENAME 2>&1
    fi
    i=$(expr $i + 1)
done
set +f # Turn globbing back on

sed -e "1,$ s-$TEST_DIR-/...absPathToRepo.../tests-g" < $TEST_DIR/$TEST_OUT_FILENAME | \
    sed -e "1,$ s/$USER/testUser/g" > $tmpfile
expand < $tmpfile | sed -e '1,$ s/ *$//' > $TEST_DIR/$TEST_OUT_FILENAME

cleanup
