#!/bin/bash

# 3-Clause BSD License
# 
# Copyright (c) 1992-2026, James Philip Rowell,
# Alpha Eleven Incorporated
# www.alpha-eleven.com
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# 
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
# 
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in
#     the documentation and/or other materials provided with the
#     distribution.
# 
#  3. Neither the name of the copyright holder, "Alpha Eleven, Inc.",
#     nor the names of its contributors may be used to endorse or
#     promote products derived from this software without specific prior
#     written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# spaces2tabs - helpful wrapper to run 'unexpand' on a list of files.

set +o noclobber
cmdName=`basename "$0"`

tmpFile=`mktemp` || exit 1

cleanup() {
    /bin/rm "$tmpFile" > /dev/null 2>&1
    exit 0
}

trap cleanup INT TERM

# Semantic Versioning 2.0.0
#
# MAJOR version for incompatible API changes
# MINOR version for added functionality in a backwards compatible manner
# PATCH version for backwards compatible bug fixes
#
VERSION=2.0.0

usageExit() {
    echo "usage: $1 [-h | --help] [OPTION]... [FILE]..."
    if [ "$2" = help ]; then
        cat - <<EOF

$cmdName is a wrapper for the command unexpand. The FILES are changed in place.

A backup copy of each original FILE is created called ".FILE.spaces" in the
directory that FILE resides.

Two special files are also created in the current directory to allow you
to review all the changes made as well as undo the changes if the results
weren't what you expected.  Namely, the files ".spaces.diff.spaces" and
".spaces.undo.spaces" which are executable.

Note: when running either of these directly, explicitly prefix the path
(almost always "./"), e.g. "./.spaces.undo.spaces", rather than typing
just the bare filename. Without the "./", your shell searches \$PATH in
order and may find and run a different, unrelated file of the same name
sitting in an earlier directory instead of the one just created here.

Note: To get rid of all the crufty leftovers:
    find . -name '.*.spaces' -type f -print0 | xargs -0 /bin/rm -f

positional arguments:
  FILE                      The file(s) to modify

optional arguments:
  -h, --help                     Display this help and exit
  -t NUMBER, --tabs=NUMBER       expands/unexpands tabs by NUMBER characters - default 8.
  --strip-trailing-whitespace    also strip trailing whitespace from every line
  --no-strip-trailing-whitespace leave trailing whitespace untouched [default]
  --version                      print out the version number and exit

Tip: If a file appears to have been created with a tabstop setting
different from your system default (assumed to be 8), first guess
that setting -- say, 4 -- and run "tabs2spaces -t 4" to see the
result. If it still doesn't look right, undo (".tabs.undo.tabs")
and try a different guess. Once the all-spaces result looks correct,
run "spaces2tabs -t 8" to re-tab it at the standard width. Each
step's undo is independent, so if you later change your mind, undo
spaces2tabs first (".spaces.undo.spaces"), then tabs2spaces
(".tabs.undo.tabs"), to cleanly reverse both steps back to the
file's true original.

EOF
        exit 0
    fi
    exit 1
}

tabSize=8
stripTrailingWS=no

#
# Parse options.  Stop when you get to the file list.
#
shopt -s extglob
while :
do
    case "$1" in
        -h|--help) usageExit $cmdName help
        ;;

        --version) echo $VERSION
            exit 0
        ;;

        -t)
            shift
            if ! [[ $1 =~ ^[0-9]+$ ]]; then
                usageExit $cmdName
            fi
            tabSize=$1
            shift
        ;;

        --tabs=+([0-9]))
            tabSize=`echo $1 | sed "s/--tabs=//"`
            if ! [[ $tabSize =~ ^[0-9]+$ ]]; then
                usageExit $cmdName
            fi
            shift
        ;;

        --strip-trailing-whitespace) stripTrailingWS=yes
            shift
        ;;

        --no-strip-trailing-whitespace) stripTrailingWS=no
            shift
        ;;

        -*) echo "$cmdName: ERROR: Invalid option '$1'."
             usageExit $cmdName
        ;;

        *) break # We're done processing arguments, so let's get on with it.
    esac
done

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=linux;;
    Darwin*)    machine=mac;;
    CYGWIN*)    machine=cygwin;;
    MINGW*)     machine=minGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac

curDir=`pwd`

echo '#!/bin/bash'  >  .spaces.undo.spaces
echo cd \"$curDir\" >> .spaces.undo.spaces
echo '#!/bin/bash'  >  .spaces.diff.spaces
echo cd \"$curDir\" >> .spaces.diff.spaces
chmod +x .spaces.undo.spaces .spaces.diff.spaces
echo '( set -x' >> .spaces.diff.spaces

while  [ $# -ne 0 ]
do
    i="$1"

    if  [ -f "$i" ] && [ -w "$i" ] ; then
        if [ "$stripTrailingWS" = yes ]; then
            unexpand -t $tabSize --first-only < "$i" | sed -e '1,$ s/ *$//' > "$tmpFile"
        else
            unexpand -t $tabSize --first-only < "$i" > "$tmpFile"
        fi
        if [ ${PIPESTATUS[0]} -ne 0 ]; then
            echo "$cmdName: ERROR: unexpand failed on \"$i\"; left unchanged." >&2
        else
            cmp -s "$i" "$tmpFile" > /dev/null 2>&1
            if [ $? -eq 1 ]; then
                d=`dirname "$i"`
                f=`basename "$i"`
                /bin/cp "$i" "$d"/."$f".spaces
                echo /bin/cp \""$d"\"/.\""$f"\".spaces \""$i"\" >> .spaces.undo.spaces
                echo "/usr/bin/diff \""$d"\"/.\""$f"\".spaces \""$i"\"; echo" >> .spaces.diff.spaces
                /bin/mv -f "$tmpFile" "$i"
                if [ "$machine" == "mac" ]; then
                    permissions=`stat -r "$d"/."$f".spaces | cut -d' ' -f3 | cut -c5-7`
                    chmod $permissions "$i"
                else
                    chmod --reference="$d"/."$f".spaces "$i"
                fi
            fi
        fi
    fi
    if [ ! -w "$i" ]; then
        echo $cmdName: WARNING: "$i" not writeable, no change made.
    fi
    shift
done

echo ') 2>&1 | grep -v "^+ echo" | less' >> .spaces.diff.spaces

cleanup
